version: 2
jobs:
  build:
    working_directory: /worker-thread
    docker:
      - image: circleci/node:4
    steps:
      - checkout
      - run:
          name: update npm
          command: sudo npm install -g npm@latest
      - run:
          name: npm install
          command: npm install
      - run:
          name: test
          command: npm test
