version: 2
jobs:
  build:
    working_directory: /worker-thread
    docker:
      - image: node:4-alpine
    steps:
      - checkout
      - run:
          name: npm install
          command: npm install
      - run:
          name: test
          command: npm test
